name: Starts
run-name: ${{ github.actor }} probando GitHub Actions
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Probando un run"
    - run: echo "${{ github.event_name }} event."
    - name: Listar archivos en el repositorio
    - run: ls ${{ github.workspace }}
    - run: echo "Este job tiene estado -> ${{ job.status }}."
      
    
