name: Starts
run-name: ${{ github.actor }} probando GitHub Actions
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Ejecutar script python y guardar salida
      run: | 
        python prueba.py > salida.txt 2>&1

    - name: Subir salida como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: salida-python
        path: salida.txt
    
